package a.a;
import com.massoftware.model.Deposito;
import com.massoftware.model.Sucursal;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Prueba extends VerticalLayout {
	
	
	
	public Prueba() {
		Design.read(this);		
	
		
//		Entity d1 = new Deposito();
//		
//		Class clazz = d1.getClass(); 
//		
//		
//		
//		if(d1 instanceof Deposito){
//			System.out.println("Si");
//			Deposito d = (Deposito) d1;
//			d.getAbreviatura()
//		}
//		
//		if(d1 instanceof EntityId){
//			System.out.println("Si");
//		}
//		
//		if(d1 instanceof Entity){
//			System.out.println("Si");
//		}
//		
//		if(d1 instanceof Object){
//			System.out.println("Si");
//		}
//		
//		
//		if(d1.getClass().equals(Deposito.class)){
//			System.out.println("Si");
//		}
//		
//		if(d1.getClass().equals(EntityId.class)){
//			System.out.println("NO");
//		}
//		
//		
//		Persona p2 = p1.clone();
//		
//		p2.equals(p1);
	}
}
